remote_theme: "mmistakes/so-simple-theme"
url: https://andrewpoland.github.io
base_url: https://andrewpoland.github.io
collections: [sections]
google_analytics: UA-121896599-1
repository: andrewPoland/andrewPoland.github.io
locale: en-us
title: "Andrew Poland"
description: "A series of guides and ramblings based on what I'm developing with"
logo: "/Assets/Sitelogo.png"
author:
  links: false  
